name: api_client
description: A simple wrapper around Dart's http client to handle common api request logic.
version: 0.1.0+1
publish_to: none

environment:
  sdk: ^3.9.0

dependencies:
  http: ^1.6.0

dev_dependencies:
  mocktail: ^1.0.4
  test: ^1.26.3
  very_good_analysis: ^10.0.0
