name: personal_blog_api
description: An new Dart Frog application
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  blog_models:
    path: packages/blog_models
  blog_repository:
    path: packages/blog_repository
  butter_cms_client:
    path: packages/butter_cms_client
  dart_frog: ^1.2.6
  http: ^1.6.0
  intl: ^0.20.2
  template_engine:
    path: packages/template_engine

dev_dependencies:
  mocktail: ^1.0.0
  test: ^1.28.0
  very_good_analysis: ^10.0.0
