name: personal_blog
description: My personal blog site, managed server-side with Dart Frog
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  api_client:
    path: packages/api_client
  blog_models:
    path: packages/blog_models
  blog_newsletter_client:
    path: packages/blog_newsletter_client
  blog_repository:
    path: packages/blog_repository
  butter_cms_client:
    path: packages/butter_cms_client
  dart_frog: ^1.2.6
  http: ^1.6.0
  intl: ^0.20.2
  subscriptions_repository:
    path: packages/subscriptions_repository
  template_engine:
    path: packages/template_engine

dev_dependencies:
  mocktail: ^1.0.0
  # Pinning to 1.25.8 to fix empty coverage issue on 1.28.0
  test: 1.25.8
  very_good_analysis: ^10.0.0
