name: template_engine
description: Package to build stringified HTML with dynamic data from templates.
version: 0.1.0+1
publish_to: none

environment:
  sdk: ^3.9.0

dependencies:
  blog_models:
    path: ../blog_models
  intl: ^0.20.2
  logging: ^1.3.0

dev_dependencies:
  mocktail: ^1.0.4
  test: ^1.28.0
  very_good_analysis: ^10.0.0
