name: blog_repository
description: A repository for fetching and managing blog data for delivery to the client.
version: 0.1.0+1
publish_to: none

environment:
  sdk: ^3.9.0

dev_dependencies:
  http: ^1.6.0
  mocktail: ^1.0.4
  test: ^1.28.0
  very_good_analysis: ^10.0.0

dependencies:
  blog_models:
    path: ../blog_models
  butter_cms_client:
    path: ../butter_cms_client
  template_engine:
    path: ../template_engine
  

