name: blog_models
description: Package containing all necessary models for fetching and presenting blog data.
version: 0.1.0+1
publish_to: none

environment:
  sdk: ^3.8.0

dev_dependencies:
  build_runner: ^2.10.4
  json_serializable: ^6.11.3
  mocktail: ^1.0.0
  test: ^1.28.0
  very_good_analysis: ^10.0.0

dependencies:
  equatable: ^2.0.7
  intl: ^0.20.2
  json_annotation: ^4.9.0
