name: subscriptions_repository
description: A repository to manage email subscriptions to the blog.
version: 0.1.0+1
publish_to: none

environment:
  sdk: ^3.9.0

dependencies:
  blog_models:
    path: ../blog_models
  blog_newsletter_client:
    path: ../blog_newsletter_client
  template_engine:
    path: ../template_engine

dev_dependencies:
  mocktail: ^1.0.4
  test: ^1.26.3
  very_good_analysis: ^10.0.0
