name: captcha_client
description: A client for verifying captcha tokens
version: 0.1.0
publish_to: none

environment:
  sdk: ^3.9.0

dependencies:
  api_client:
    path: ../api_client
  blog_models:
    path: ../blog_models
  http: ^1.6.0

dev_dependencies:
  mocktail: ^1.0.4
  test: ^1.26.3
  very_good_analysis: ^10.0.0
