name: butter_cms_client
description: A Very Good Project created by Very Good CLI.
version: 0.1.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  api_client:
    path: ../api_client
  blog_models:
    path: ../blog_models
  http: ^1.6.0

dev_dependencies:
  mocktail: ^1.0.0
  test: ^1.28.0
  very_good_analysis: ^10.0.0
