name: Blog Newsletter Client Verify and Test

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  pull_request:
    branches:
      - master
      - main
    paths:
      - ".github/workflows/blog_newsletter_client_verify_and_test.yaml"
      - "packages/blog_newsletter_client/**"
      - "packages/blog_models/**"
  push:
    branches:
      - master
      - main
    paths:
      - ".github/workflows/**"
      - "packages/blog_newsletter_client/**"
      - "packages/blog_models/**"

jobs:
  verify_and_test:
    name: Verify and Test
    uses: VeryGoodOpenSource/very_good_workflows/.github/workflows/dart_package.yml@main
    with:
      working_directory: packages/blog_newsletter_client
      dart_sdk: stable
      min_coverage: 100
