name: Blog Update Handler Verify and Test

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  pull_request:
    branches:
      - master
      - main
    paths:
      - ".github/workflows/blog_update_handler_verify_and_test.yaml"
      - "blog_update_handler/**"

  push:
    branches:
      - master
      - main
    paths:
      - ".github/workflows/**"
      - "blog_update_handler/**"


jobs:
  verify_and_test:
    name: Verify and Test
    uses: VeryGoodOpenSource/very_good_workflows/.github/workflows/dart_package.yml@main
    with:
      working_directory: blog_update_handler
      dart_sdk: stable
      min_coverage: 100
